version: '2'
services:
  db:
    image: mysql:5.5
    container_name: database
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "ca"
      MYSQL_USER: "ca"
      MYSQL_PASSWORD: "ca"
      MYSQL_ROOT_PASSWORD: "root" 
  nginx:
    build: ./containers/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/var/www/:/var/www/html/
    links:
      - php5.5-fpm:fpm 
  php5.5-fpm:
    build: ./containers/php5.5-fpm
    container_name: php5.5-fpm
    volumes:
      - ./data/var/www/:/var/www/html/
    ports:
      - "9000:9000"
  #php7.1-fpm:
  #  build: ./containers/php7.1-fpm
  #  container_name: php7.1-fpm
  #  volumes:
  #    - ./data/var/www/:/var/www/html/
  #  ports:
  #    - "9000:9000"
