version: '2'
services:
  db:
    image: rmarkov/mysql:5.5
    container_name: database
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "ca"
      MYSQL_USER: "ca"
      MYSQL_PASSWORD: "ca"
      MYSQL_ROOT_PASSWORD: "root" 
  nginx:
    image: rmarkov/nginx:ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/var/www/:/var/www/html/
    links:
      - fpm
  fpm:
    extends:
      file: common-services.yml
      service: php5.5-fpm
